export const loginActions = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_RESET: 'LOGIN_RESET',
    LOGIN_REFRESHING: 'LOGIN_REFRESHING',
};